# Generated by Django 4.1.2 on 2022-10-17 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_tag_alter_category_name_alter_post_category_post_tag"),
    ]

    operations = [
        migrations.CreateModel(
            name="Social",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
            ],
        ),
    ]
