# Generated by Django 4.1.2 on 2022-10-17 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_alter_social_options_social_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("page", models.CharField(max_length=50)),
            ],
            options={"ordering": ["title"],},
        ),
    ]
