# Generated by Django 4.1.2 on 2022-10-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0010_localuser_alter_post_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[("DF", "Draft"), ("DM", "Demo"), ("PB", "Published")],
                default="DF",
                max_length=2,
            ),
        ),
    ]
