# Generated by Django 4.1.2 on 2022-10-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0014_tag_link_alter_tag_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
