# Generated by Django 4.1 on 2022-10-12 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_comment_post_post_author_post_category_post_slug_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Lifestyle", max_length=20)),
            ],
            options={"ordering": ["name"],},
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(default="Nature Lifestyle", max_length=30),
        ),
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="posts.category",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="tag",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="posts.tag",
            ),
        ),
    ]
