# Generated by Django 4.1.2 on 2022-10-17 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0007_info"),
    ]

    operations = [
        migrations.AddField(
            model_name="banner",
            name="name",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
    ]
