# Generated by Django 4.1.2 on 2022-10-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0008_banner_name"),
    ]

    operations = [
        migrations.AlterModelOptions(name="banner", options={"ordering": ["-name"]},),
        migrations.AddField(
            model_name="info",
            name="complement",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
