# Generated by Django 4.1.2 on 2022-10-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0011_alter_post_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[
                    ("DF", "Draft"),
                    ("BN", "Banner"),
                    ("DM", "Demo"),
                    ("PB", "Published"),
                ],
                default="DF",
                max_length=2,
            ),
        ),
    ]
