# Generated by Django 4.1.2 on 2022-10-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0013_banner_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag", name="link", field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
